language: groovy

sudo: required
dist: trusty

jdk:
- oraclejdk7

before_script:
- "export DISPLAY=:99.0" 
- "sh -e /etc/init.d/xvfb start"

before_install:
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome.deb
- sudo dpkg -i chrome.deb
- sudo apt-get install -f
- curl -s get.sdkman.io | bash
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails 2.4.3 

branches:
  only:
    - master

script: grails test-app -Dgeb.env=chrome functional:cucumber --non-interactive --stacktrace --verbose