language: groovy

jdk:
- oraclejdk7

before_script:
- "export DISPLAY=:99.0" 
- "sh -e /etc/init.d/xvfb start"

before_install:
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get update
- sudo apt-get install google-chrome-stable
- curl -s get.sdkman.io | bash
- source "$HOME/.sdkman/bin/sdkman-init.sh"
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails 2.4.3 

branches:
  only:
    - master

script: grails test-app -Dgeb.env=chrome functional:cucumber --non-interactive --stacktrace --verbose