package sistemadevagasdeestacionamento

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    /**
     * Array of controller/action combinations that will be authenticated against the user's
     * role. The map also includes the roles which the controller/action pair will match
     * against.
     */
    static authenticatedActions = [
        [controller: 'parkingSpace', action: '*', roles: ['User']],
        [controller: 'user', action: '*', roles: ['User']]
    ]

    def filters = {
        all(controller: '*', action: '*') {
            before = {
                // Get the map within the authenticated actions which pertain to the current
                // controller and view.
                def authRoles = authenticatedActions.find { (it.controller == controllerName) && ((it.action == '*') || (it.action == actionName)) }

                if (authRoles) {
                    // Perform the access control for each of the roles provided in the authRoles
                    accessControl {
                        authRoles.roles.each { roleName ->
                            role(roleName)
                        }
                    }
                } else {
                    return true
                }
            }
        }

    }
}